spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
app.data.path=data/
server.port=${PORT:8080}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.path=src/main/webapp/images/uploads/
